apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  # `|-` is for declaring a multi-line string
  # To check boolean values explicity, we use
  # (kindIs "invalid") to check if the value is nil.
  config.js: |-
    const config = {
    {{- if .Values.baseUrl }}
    baseUrl: {{ .Values.baseUrl | quote }},
    {{- end }}
    {{- if not (kindIs "invalid" .Values.debug) }}
    debug: {{ .Values.debug }},
    {{- end }}
    {{- if not (kindIs "invalid" .Values.db.ssl) }}
    dbSSL: {{ .Values.db.ssl }},
    {{- end }}
    //db: "postgres://{{ template "binder-launches.dbURL" . }}"
    db: {{ printf "postgres://%s" (include "binder-launches.dbURL" .) | quote }}
    };
    module.exports = config;
